apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sagi-l/ci-dashboard.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
