apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-dashboard
  namespace: ci-dashboard
  labels:
    app: ci-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-dashboard
  template:
    metadata:
      labels:
        app: ci-dashboard
    spec:
      serviceAccountName: ci-dashboard
      containers:
        - name: ci-dashboard
          image: sabichon/ci-dashboard:134
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "134"  # Jenkins will update this
            - name: MOCK_MODE
              value: "false"
            - name: JENKINS_URL
              value: "http://jenkins.jenkins.svc.cluster.local:8080"
            - name: JENKINS_JOB_NAME
              value: "ci-dashboard"
            - name: JENKINS_USER
              valueFrom:
                secretKeyRef:
                  name: jenkins-credentials
                  key: username
                  optional: true
            - name: JENKINS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jenkins-credentials
                  key: token
                  optional: true
            - name: ARGOCD_URL
              value: "https://argocd-server.argocd.svc.cluster.local"
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-credentials
                  key: token
                  optional: true
            - name: ARGOCD_APP_NAME
              value: "ci-dashboard"
            - name: K8S_NAMESPACE
              value: "ci-dashboard"
            - name: GITHUB_APP_REPO
              value: "https://github.com/sagi-l/ci-dashboard"
            - name: GITHUB_INFRA_REPO
              value: "https://github.com/sagi-l/ci-cd-platform-k8s"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: token
            - name: GITHUB_REPO_OWNER
              value: "sagi-l"
            - name: GITHUB_REPO_NAME
              value: "ci-dashboard"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
