apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-dashboard-ingress
  namespace: ci-dashboard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: cicd-lab.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ci-dashboard
            port:
              number: 80
