apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-dashboard
  namespace: ci-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-dashboard-reader
  namespace: ci-dashboard
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-dashboard-reader
  namespace: ci-dashboard
subjects:
  - kind: ServiceAccount
    name: ci-dashboard
    namespace: ci-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-dashboard-reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-dashboard-namespace-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-dashboard-namespace-reader
subjects:
  - kind: ServiceAccount
    name: ci-dashboard
    namespace: ci-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ci-dashboard-namespace-reader
